name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push amd64 image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t umbertodefilippis/3gm_haa_raw2cal:latest \
            --push .
